## Bad Debt Prediction

### Load the datasets

In [1]:
import pandas as pd
import numpy as np

In [2]:
# loading the datasets:

def load_data():
    print("Loading datasets....")

    data_df = pd.read_excel("Data.xlsm",sheet_name="DataV2")
    additional_df = pd.read_excel("Additional Info.xlsx",sheet_name="Additional info")

    print("Datasets loaded successfully !")

    print(f"\n Data dataset")
    print(data_df.head())

    print(f"\n Additional Dataset")
    print(additional_df.head())
    return data_df, additional_df

### Merging the datasets

In [3]:
def merge_data(data_df,additional_df):

    print("\nMerging datasets.....")

    merged_df = pd.merge(data_df,additional_df,on="Customer",how="left")
    print("Datasets merged successfully..")
    print("merged datasets shape:",merged_df.shape)

    return merged_df

# Load datasets
data_df, additional_df = load_data()

# Merge datasets
merged_df = merge_data(data_df,additional_df)

# View the merged data's
print("\n Merged datasets preview")
print(merged_df.head())

Loading datasets....
Datasets loaded successfully !

 Data dataset
  OUTCOME    Customer  RISK_SCORE BUREAU_ENQUIRIES_12_MONTHS  \
0    Good  2975536526         628      queries 12 Months 1-2
1    Good  2999806086         813      queries 12 Months 1-2
2    Good  2800835182        1012      queries 12 Months 4-5
3    Good  2975640662         415      queries 12 Months 4-5
4    Good  2979232086         556      queries 12 Months 1-2

              LICENCE_AVAILABLE                    RESIDENTIAL  \
0  Driver Licence Check Missing                         Rented
1      Driver Licence Check Yes                         Rented
2      Driver Licence Check Yes                          Owned
3  Driver Licence Check Missing                         Rented
4  Driver Licence Check Missing  Board or Living With Relative

             BUREAU_DEFAULT CD_OCCUPATION CD_STS_RESIDENTIAL  DEFAULT_AMT  \
0  Default Current- Missing             E                  R            0
1  Default Current- Missing             E                  R            0
2  Default Current- Missing             E                  O            0
3     Default Current1-1000             E                  R          459
4  Default Current- Missing             U                  B            0

   ...  DEFAULTS_12M  NO_MONTHS_VCR221  NO_STATUS_VCR183  CD_STS_VCR184  \
0  ...             0                 0                 -              -
1  ...             0                 0                 1              -
2  ...             0                 0                 0              -
3  ...             0                 0                 -              -
4  ...             0                 0                 -              -

   NO_MONTHS_VCR228 NO_MONTHS_VCR226 NO_SUM_VCR053  NO_MONTHS_VCR258  \
0                 0                0             0                 0
1                24                0          4000                23
2                24                0        380277                24
3                 0                0             0                 0
4                 0                0             0                 0

   SCORECARD  NO_SCORE
0      TAR1A       724
1      TAR1A       775
2     SFJR1A       815
3     HSHSOL       328
4      TAR1A       692

[5 rows x 23 columns]

 Additional Dataset
     Customer SCORE_INDICATOR_CR22  SCORE_CR22 SCORE_BAND_CR22  NO_SCORE_CR21  \
0  2984743758       Clean Positive       373.0               H          608.0
1  2984205798       Clean Positive      1024.0               A          827.0
2  2983553714       Clean Positive      1005.0               A          833.0
3  2972077238       Clean Positive       506.0               G          724.0
4  2975514910       Dirty Positive        98.0               H          484.0

  SCORECARD_CR21  RISK_RELATIVE_CR21  RISK_RELATIVE_ODDS_CR21  \
0          CTS1A                4.09                    16.91
1          CTSSH               18.66                    77.17
2          CTSSH               19.45                    80.45
3          CTS1A                9.14                    37.79
4          CTSDP                1.73                     7.16

   NO_MONTHS_OLDEST_ACCOUNT  OPEN_ACCT_CR22  ...  WORST_24M  \
0                         0               0  ...          0
1                       268               2  ...          0
2                       339               6  ...          0
3                         0               0  ...          0
4                         4               1  ...          3

                 DOC_TYPE  VISA_TYPE  EMPLOYED_STATUS  EMPLOYED_TYPE  \
0  Intl Passport and Visa  Work Visa                E              F
1       AU Driver Licence   Resident                R              U
2       AU Driver Licence   Resident                E              F
3       AU Driver Licence   Resident                E              P
4       AU Driver Licence   Resident                E              F

   EMPLOYED_NO_MTHS  NO_ADDRESS_AT_MONTHS  CD_STS_RESIDENTIAL  AGENCY_AMT  \
0               3.0                   0.0                   R         NaN
1               0.0                 120.0                   O         NaN
2             131.0                  24.0                   O         NaN
3               2.0                   2.0                   R         NaN
4              20.0                   4.0                   R         NaN

   MTH_TILL_AGENCY
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN

[5 rows x 76 columns]

Merging datasets.....
Datasets merged successfully..
merged datasets shape: (95309, 98)

 Merged datasets preview
  OUTCOME    Customer  RISK_SCORE BUREAU_ENQUIRIES_12_MONTHS  \
0    Good  2975536526         628      queries 12 Months 1-2
1    Good  2999806086         813      queries 12 Months 1-2
2    Good  2800835182        1012      queries 12 Months 4-5
3    Good  2975640662         415      queries 12 Months 4-5
4    Good  2979232086         556      queries 12 Months 1-2

              LICENCE_AVAILABLE                    RESIDENTIAL  \
0  Driver Licence Check Missing                         Rented
1      Driver Licence Check Yes                         Rented
2      Driver Licence Check Yes                          Owned
3  Driver Licence Check Missing                         Rented
4  Driver Licence Check Missing  Board or Living With Relative

             BUREAU_DEFAULT CD_OCCUPATION CD_STS_RESIDENTIAL_x  DEFAULT_AMT  \
0  Default Current- Missing             E                    R            0
1  Default Current- Missing             E                    R            0
2  Default Current- Missing             E                    O            0
3     Default Current1-1000             E                    R          459
4  Default Current- Missing             U                    B            0

   ...  WORST_24M                DOC_TYPE  VISA_TYPE  EMPLOYED_STATUS  \
0  ...        0.0  Intl Passport and Visa  Work Visa                E
1  ...        1.0       AU Driver Licence   Resident                E
2  ...        0.0       AU Driver Licence   Resident                E
3  ...        0.0  Intl Passport and Visa   Resident                E
4  ...        0.0  Intl Passport and Visa  Work Visa                U

   EMPLOYED_TYPE EMPLOYED_NO_MTHS NO_ADDRESS_AT_MONTHS  CD_STS_RESIDENTIAL_y  \
0              F              1.0                  1.0                     R
1              F             86.0                 49.0                     R
2              F             61.0                129.0                     O
3              F             15.0                 60.0                     R
4              U              0.0                  1.0                     B

   AGENCY_AMT  MTH_TILL_AGENCY
0         NaN              NaN
1         NaN              NaN
2         NaN              NaN
3         NaN              NaN
4       60.01             16.0

[5 rows x 98 columns]

In [4]:
merged_df

,OUTCOME,Customer,RISK_SCORE,BUREAU_ENQUIRIES_12_MONTHS,LICENCE_AVAILABLE,RESIDENTIAL,BUREAU_DEFAULT,CD_OCCUPATION,CD_STS_RESIDENTIAL_x,DEFAULT_AMT,...,WORST_24M,DOC_TYPE,VISA_TYPE,EMPLOYED_STATUS,EMPLOYED_TYPE,EMPLOYED_NO_MTHS,NO_ADDRESS_AT_MONTHS,CD_STS_RESIDENTIAL_y,AGENCY_AMT,MTH_TILL_AGENCY
0,Good,2975536526,628,queries 12 Months 1-2,Driver Licence Check Missing,Rented,Default Current- Missing,E,R,0,...,0.0,Intl Passport and Visa,Work Visa,E,F,1.0,1.0,R,NaN,NaN
1,Good,2999806086,813,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,86.0,49.0,R,NaN,NaN
2,Good,2800835182,1012,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,E,O,0,...,0.0,AU Driver Licence,Resident,E,F,61.0,129.0,O,NaN,NaN
3,Good,2975640662,415,queries 12 Months 4-5,Driver Licence Check Missing,Rented,Default Current1-1000,E,R,459,...,0.0,Intl Passport and Visa,Resident,E,F,15.0,60.0,R,NaN,NaN
4,Good,2979232086,556,queries 12 Months 1-2,Driver Licence Check Missing,Board or Living With Relative,Default Current- Missing,U,B,0,...,0.0,Intl Passport and Visa,Work Visa,U,U,0.0,1.0,B,60.01,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95304,Good,2999821794,1043,queries 12 Months 1-2,Driver Licence Check Yes,Owned,Default Current- Missing,R,O,0,...,0.0,AU Driver Licence,Resident,R,U,0.0,120.0,O,NaN,NaN
95305,Good,2811821694,589,queries 12 Months 6,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,1.0,6.0,R,NaN,NaN
95306,Good,2971478930,746,queries 12 Months 3,Driver Licence Check Missing,Owned,Default Current- Missing,S,O,0,...,0.0,AU Passport,Resident,S,F,0.0,125.0,O,NaN,NaN
95307,Bad,2974937898,868,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,U,R,0,...,0.0,AU Driver Licence,Resident,U,U,0.0,274.0,R,304.39,4.0
95308,Good,2977362690,1062,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,S,O,0,...,1.0,AU Driver Licence,Resident,S,F,120.0,120.0,O,NaN,NaN

### Removing duplicates

In [5]:
def remove_duplicates(merged_df):
    print("Removing the duplicates....")

    merged_df = merged_df.drop_duplicates()
    print("Duplicates removed sucessfully...")
    print(f"Dataset shape : {merged_df.shape}")

    return merged_df
merged_df = remove_duplicates(merged_df)
print("Remaining duplicates :",merged_df.duplicated().sum())

Removing the duplicates....
Duplicates removed sucessfully...
Dataset shape : (92142, 98)
Remaining duplicates : 0

In [6]:
merged_df.shape

(92142, 98)

In [7]:
merged_df

,OUTCOME,Customer,RISK_SCORE,BUREAU_ENQUIRIES_12_MONTHS,LICENCE_AVAILABLE,RESIDENTIAL,BUREAU_DEFAULT,CD_OCCUPATION,CD_STS_RESIDENTIAL_x,DEFAULT_AMT,...,WORST_24M,DOC_TYPE,VISA_TYPE,EMPLOYED_STATUS,EMPLOYED_TYPE,EMPLOYED_NO_MTHS,NO_ADDRESS_AT_MONTHS,CD_STS_RESIDENTIAL_y,AGENCY_AMT,MTH_TILL_AGENCY
0,Good,2975536526,628,queries 12 Months 1-2,Driver Licence Check Missing,Rented,Default Current- Missing,E,R,0,...,0.0,Intl Passport and Visa,Work Visa,E,F,1.0,1.0,R,NaN,NaN
1,Good,2999806086,813,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,86.0,49.0,R,NaN,NaN
2,Good,2800835182,1012,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,E,O,0,...,0.0,AU Driver Licence,Resident,E,F,61.0,129.0,O,NaN,NaN
3,Good,2975640662,415,queries 12 Months 4-5,Driver Licence Check Missing,Rented,Default Current1-1000,E,R,459,...,0.0,Intl Passport and Visa,Resident,E,F,15.0,60.0,R,NaN,NaN
4,Good,2979232086,556,queries 12 Months 1-2,Driver Licence Check Missing,Board or Living With Relative,Default Current- Missing,U,B,0,...,0.0,Intl Passport and Visa,Work Visa,U,U,0.0,1.0,B,60.01,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95304,Good,2999821794,1043,queries 12 Months 1-2,Driver Licence Check Yes,Owned,Default Current- Missing,R,O,0,...,0.0,AU Driver Licence,Resident,R,U,0.0,120.0,O,NaN,NaN
95305,Good,2811821694,589,queries 12 Months 6,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,1.0,6.0,R,NaN,NaN
95306,Good,2971478930,746,queries 12 Months 3,Driver Licence Check Missing,Owned,Default Current- Missing,S,O,0,...,0.0,AU Passport,Resident,S,F,0.0,125.0,O,NaN,NaN
95307,Bad,2974937898,868,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,U,R,0,...,0.0,AU Driver Licence,Resident,U,U,0.0,274.0,R,304.39,4.0
95308,Good,2977362690,1062,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,S,O,0,...,1.0,AU Driver Licence,Resident,S,F,120.0,120.0,O,NaN,NaN

### View the column summary

In [ ]:
def column_summary(df):

    summary_df = pd.DataFrame({
        "Column_Name": df.columns,
        "Data_Type": df.dtypes.values,
        "Null_Count": df.isnull().sum().values,
        "Null_Percentage": round((df.isnull().sum() / len(df)) * 100, 2).values,
        "Unique_Values": df.nunique().values
    })

    summary_df = summary_df.sort_values(
        by="Null_Percentage",
        ascending=False
    )

    return summary_df


# Generate report
summary_df = column_summary(merged_df)

# View report
print(summary_df)
'''
#Save report
summary_df.to_csv(
    "Column_Summary_Report.csv",
    index=False
) '''

         Column_Name Data_Type  Null_Count  Null_Percentage  Unique_Values
96        AGENCY_AMT   float64       83522            90.64           8011
97   MTH_TILL_AGENCY   float64       83522            90.64             20
91   EMPLOYED_STATUS       str       11102            12.05              9
92     EMPLOYED_TYPE       str       11102            12.05              5
93  EMPLOYED_NO_MTHS   float64       11102            12.05            373
..               ...       ...         ...              ...            ...
13      DEFAULTS_12M     int64           0             0.00              6
14  NO_MONTHS_VCR221     int64           0             0.00             13
15  NO_STATUS_VCR183    object           0             0.00             12
16     CD_STS_VCR184    object           0             0.00             11
17  NO_MONTHS_VCR228     int64           0             0.00             25

[98 rows x 5 columns]

### Dropping the unwanted columns

In [12]:
def drop_unwanted_columns(df):

    columns_to_drop = [
        "Customer",
        "WORST_3M",
        "WORST_1M",
        "WORST_18M",
        "WORST_12M",
        "WORST_24M",
        "MTH_TILL_AGENCY",
        "AGENCY_AMT"
    ]

    print("Dropping unwanted columns...")

    df = df.drop(columns =columns_to_drop,errors="ignore")

    print("Dropping the columns sucessfully..")
    print(f"Current shape : {df.shape}")
    return df

merged_df = drop_unwanted_columns(merged_df)
print(merged_df.columns.tolist())

Dropping unwanted columns...
Dropping the columns sucessfully..
Current shape : (92142, 90)
['OUTCOME', 'RISK_SCORE', 'BUREAU_ENQUIRIES_12_MONTHS', 'LICENCE_AVAILABLE', 'RESIDENTIAL', 'BUREAU_DEFAULT', 'CD_OCCUPATION', 'CD_STS_RESIDENTIAL_x', 'DEFAULT_AMT', 'ENQUIRIES_6M', 'ENQUIRIES_12M', 'DEROGATORIES', 'DEFAULTS_12M', 'NO_MONTHS_VCR221', 'NO_STATUS_VCR183', 'CD_STS_VCR184', 'NO_MONTHS_VCR228', 'NO_MONTHS_VCR226', 'NO_SUM_VCR053', 'NO_MONTHS_VCR258', 'SCORECARD', 'NO_SCORE', 'SCORE_INDICATOR_CR22', 'SCORE_CR22', 'SCORE_BAND_CR22', 'NO_SCORE_CR21', 'SCORECARD_CR21', 'RISK_RELATIVE_CR21', 'RISK_RELATIVE_ODDS_CR21', 'NO_MONTHS_OLDEST_ACCOUNT', 'OPEN_ACCT_CR22', 'CLOSED_ACCT_CR22', 'MORTGAGE_CR22', 'CREDIT_CARD_CR22', 'TELCO_CR22', 'UTILITIES_CR22', 'OVERDRAFT_CR22', 'PERSONAL_LOAN_CR22', 'AUTO_LOAN_CR22', 'CREDIT_CARD_AMT_CR22', 'OVERDRAFT_AMT_CR22', 'PERSONAL_LOAN_AMT_CR22', 'AUTO_LOAN_AMT_CR22', 'OPEN_ACCT_CR21', 'CLOSED_ACCT_CR21', 'MORTGAGE_CR21', 'CREDIT_CARD_CR21', 'TELCO_CR21', 'UTILITIES_CR21', 'OVERDRAFT_CR21', 'PERSONAL_LOAN_CR21', 'AUTO_LOAN_CR21', 'CREDIT_CARD_AMT_CR21', 'OVERDRAFT_AMT_CR21', 'PERSONAL_LOAN_AMT_CR21', 'AUTO_LOAN_AMT_CR21', 'ENQUIRY_CNT_CR22', 'ENQUIRY_CNT_1M_CR22', 'ENQUIRY_CNT_3M_CR22', 'ENQUIRY_CNT_6M_CR22', 'ENQUIRY_CNT_12M_CR22', 'ENQUIRY_CNT_CR21', 'ENQUIRY_CNT_1M_CR21', 'ENQUIRY_CNT_3M_CR21', 'ENQUIRY_CNT_6M_CR21', 'ENQUIRY_CNT_12M_CR21', 'ENQUIRY_MAX_AMT_1M', 'ENQUIRY_MAX_AMT_3M', 'ENQUIRY_MAX_AMT_6M', 'ENQUIRY_MAX_AMT_12M', 'DEFAULT_CNT_CR22', 'DEFAULT_OPEN_CNT_CR22', 'DEFAULT_CNT_3M_CR22', 'DEFAULT_CNT_6M_CR22', 'DEFAULT_CNT_12M_CR22', 'DEFAULT_UNPAID_AMT_CR22', 'DEFAULT_CNT_CR21', 'DEFAULT_OPEN_CNT_CR21', 'DEFAULT_UNPAID_AMT_CR21', 'DEFAULT_CNT_3M_CR21', 'DEFAULT_CNT_6M_CR21', 'DEFAULT_CNT_12M_CR21', 'WORST_6M', 'DOC_TYPE', 'VISA_TYPE', 'EMPLOYED_STATUS', 'EMPLOYED_TYPE', 'EMPLOYED_NO_MTHS', 'NO_ADDRESS_AT_MONTHS', 'CD_STS_RESIDENTIAL_y']

In [13]:
merged_df

,OUTCOME,RISK_SCORE,BUREAU_ENQUIRIES_12_MONTHS,LICENCE_AVAILABLE,RESIDENTIAL,BUREAU_DEFAULT,CD_OCCUPATION,CD_STS_RESIDENTIAL_x,DEFAULT_AMT,ENQUIRIES_6M,...,DEFAULT_CNT_6M_CR21,DEFAULT_CNT_12M_CR21,WORST_6M,DOC_TYPE,VISA_TYPE,EMPLOYED_STATUS,EMPLOYED_TYPE,EMPLOYED_NO_MTHS,NO_ADDRESS_AT_MONTHS,CD_STS_RESIDENTIAL_y
0,Good,628,queries 12 Months 1-2,Driver Licence Check Missing,Rented,Default Current- Missing,E,R,0,2,...,0.0,0.0,0.0,Intl Passport and Visa,Work Visa,E,F,1.0,1.0,R
1,Good,813,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,2,...,0.0,0.0,1.0,AU Driver Licence,Resident,E,F,86.0,49.0,R
2,Good,1012,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,E,O,0,5,...,0.0,0.0,0.0,AU Driver Licence,Resident,E,F,61.0,129.0,O
3,Good,415,queries 12 Months 4-5,Driver Licence Check Missing,Rented,Default Current1-1000,E,R,459,2,...,0.0,0.0,0.0,Intl Passport and Visa,Resident,E,F,15.0,60.0,R
4,Good,556,queries 12 Months 1-2,Driver Licence Check Missing,Board or Living With Relative,Default Current- Missing,U,B,0,2,...,0.0,0.0,0.0,Intl Passport and Visa,Work Visa,U,U,0.0,1.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95304,Good,1043,queries 12 Months 1-2,Driver Licence Check Yes,Owned,Default Current- Missing,R,O,0,2,...,0.0,0.0,0.0,AU Driver Licence,Resident,R,U,0.0,120.0,O
95305,Good,589,queries 12 Months 6,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,3,...,0.0,0.0,1.0,AU Driver Licence,Resident,E,F,1.0,6.0,R
95306,Good,746,queries 12 Months 3,Driver Licence Check Missing,Owned,Default Current- Missing,S,O,0,3,...,0.0,0.0,0.0,AU Passport,Resident,S,F,0.0,125.0,O
95307,Bad,868,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,U,R,0,2,...,0.0,0.0,0.0,AU Driver Licence,Resident,U,U,0.0,274.0,R
95308,Good,1062,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,S,O,0,4,...,0.0,0.0,0.0,AU Driver Licence,Resident,S,F,120.0,120.0,O

### Imputing the missing values using "Mode and Median"

In [14]:
def impute_missing_values(df):
    print("Imputing the missing values")

    # Numeric columns:
    numerical_cols = df.select_dtypes(include=["int64","float64"]).columns

    for col in numerical_cols:
        df[col] = df[col].fillna(df[col].median())

    # categoriacal columns:
    categorical_cols = df.select_dtypes(include=["object"]).columns

    for col in categorical_cols:
        df[col] = df[col].fillna(df[col].mode()[0])

    print("Missiing values are Imputed successfully..")

    return df
merged_df = impute_missing_values(merged_df)
print(merged_df.isnull().sum().sum())

Imputing the missing values

C:\Users\ompra\AppData\Local\Temp\ipykernel_8160\2243468637.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object"]).columns

Missiing values are Imputed successfully..
0

In [17]:
merged_df.isnull().sum()

OUTCOME                       0
RISK_SCORE                    0
BUREAU_ENQUIRIES_12_MONTHS    0
LICENCE_AVAILABLE             0
RESIDENTIAL                   0
                             ..
EMPLOYED_STATUS               0
EMPLOYED_TYPE                 0
EMPLOYED_NO_MTHS              0
NO_ADDRESS_AT_MONTHS          0
CD_STS_RESIDENTIAL_y          0
Length: 90, dtype: int64

In [18]:
merged_df.to_csv(
    "cleaned_data.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.