## Bad Debt Prediction

### Load the datasets

In [1]:
import pandas as pd
import numpy as np

In [2]:
# loading the datasets:

def load_data():
    print("Loading datasets....")

    data_df = pd.read_excel("Data.xlsm",sheet_name="DataV2")
    additional_df = pd.read_excel("Additional Info.xlsx",sheet_name="Additional info")

    print("Datasets loaded successfully !")

    print(f"\n Data dataset")
    print(data_df.head())

    print(f"\n Additional Dataset")
    print(additional_df.head())
    return data_df, additional_df

### Merging the datasets

In [3]:
def merge_data(data_df,additional_df):

    print("\nMerging datasets.....")

    merged_df = pd.merge(data_df,additional_df,on="Customer",how="left")
    print("Datasets merged successfully..")
    print("merged datasets shape:",merged_df.shape)

    return merged_df

# Load datasets
data_df, additional_df = load_data()

# Merge datasets
merged_df = merge_data(data_df,additional_df)

# View the merged data's
print("\n Merged datasets preview")
print(merged_df.head())    

def remove_rejected_records(df):

    print("Removing rejected records...")

    df = df[
        df["OUTCOME"] != "Rejected - Policy Decline"
    ]

    print("Rejected records removed successfully!")
    print(df["OUTCOME"].value_counts())

    return df

merged_df = merged_df[
    merged_df["OUTCOME"] != "Rejected - Policy Decline"
]

Loading datasets....
Datasets loaded successfully !

 Data dataset
  OUTCOME    Customer  RISK_SCORE BUREAU_ENQUIRIES_12_MONTHS  \
0    Good  2975536526         628      queries 12 Months 1-2
1    Good  2999806086         813      queries 12 Months 1-2
2    Good  2800835182        1012      queries 12 Months 4-5
3    Good  2975640662         415      queries 12 Months 4-5
4    Good  2979232086         556      queries 12 Months 1-2

              LICENCE_AVAILABLE                    RESIDENTIAL  \
0  Driver Licence Check Missing                         Rented
1      Driver Licence Check Yes                         Rented
2      Driver Licence Check Yes                          Owned
3  Driver Licence Check Missing                         Rented
4  Driver Licence Check Missing  Board or Living With Relative

             BUREAU_DEFAULT CD_OCCUPATION CD_STS_RESIDENTIAL  DEFAULT_AMT  \
0  Default Current- Missing             E                  R            0
1  Default Current- Missing             E                  R            0
2  Default Current- Missing             E                  O            0
3     Default Current1-1000             E                  R          459
4  Default Current- Missing             U                  B            0

   ...  DEFAULTS_12M  NO_MONTHS_VCR221  NO_STATUS_VCR183  CD_STS_VCR184  \
0  ...             0                 0                 -              -
1  ...             0                 0                 1              -
2  ...             0                 0                 0              -
3  ...             0                 0                 -              -
4  ...             0                 0                 -              -

   NO_MONTHS_VCR228 NO_MONTHS_VCR226 NO_SUM_VCR053  NO_MONTHS_VCR258  \
0                 0                0             0                 0
1                24                0          4000                23
2                24                0        380277                24
3                 0                0             0                 0
4                 0                0             0                 0

   SCORECARD  NO_SCORE
0      TAR1A       724
1      TAR1A       775
2     SFJR1A       815
3     HSHSOL       328
4      TAR1A       692

[5 rows x 23 columns]

 Additional Dataset
     Customer SCORE_INDICATOR_CR22  SCORE_CR22 SCORE_BAND_CR22  NO_SCORE_CR21  \
0  2984743758       Clean Positive       373.0               H          608.0
1  2984205798       Clean Positive      1024.0               A          827.0
2  2983553714       Clean Positive      1005.0               A          833.0
3  2972077238       Clean Positive       506.0               G          724.0
4  2975514910       Dirty Positive        98.0               H          484.0

  SCORECARD_CR21  RISK_RELATIVE_CR21  RISK_RELATIVE_ODDS_CR21  \
0          CTS1A                4.09                    16.91
1          CTSSH               18.66                    77.17
2          CTSSH               19.45                    80.45
3          CTS1A                9.14                    37.79
4          CTSDP                1.73                     7.16

   NO_MONTHS_OLDEST_ACCOUNT  OPEN_ACCT_CR22  ...  WORST_24M  \
0                         0               0  ...          0
1                       268               2  ...          0
2                       339               6  ...          0
3                         0               0  ...          0
4                         4               1  ...          3

                 DOC_TYPE  VISA_TYPE  EMPLOYED_STATUS  EMPLOYED_TYPE  \
0  Intl Passport and Visa  Work Visa                E              F
1       AU Driver Licence   Resident                R              U
2       AU Driver Licence   Resident                E              F
3       AU Driver Licence   Resident                E              P
4       AU Driver Licence   Resident                E              F

   EMPLOYED_NO_MTHS  NO_ADDRESS_AT_MONTHS  CD_STS_RESIDENTIAL  AGENCY_AMT  \
0               3.0                   0.0                   R         NaN
1               0.0                 120.0                   O         NaN
2             131.0                  24.0                   O         NaN
3               2.0                   2.0                   R         NaN
4              20.0                   4.0                   R         NaN

   MTH_TILL_AGENCY
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN

[5 rows x 76 columns]

Merging datasets.....
Datasets merged successfully..
merged datasets shape: (95309, 98)

 Merged datasets preview
  OUTCOME    Customer  RISK_SCORE BUREAU_ENQUIRIES_12_MONTHS  \
0    Good  2975536526         628      queries 12 Months 1-2
1    Good  2999806086         813      queries 12 Months 1-2
2    Good  2800835182        1012      queries 12 Months 4-5
3    Good  2975640662         415      queries 12 Months 4-5
4    Good  2979232086         556      queries 12 Months 1-2

              LICENCE_AVAILABLE                    RESIDENTIAL  \
0  Driver Licence Check Missing                         Rented
1      Driver Licence Check Yes                         Rented
2      Driver Licence Check Yes                          Owned
3  Driver Licence Check Missing                         Rented
4  Driver Licence Check Missing  Board or Living With Relative

             BUREAU_DEFAULT CD_OCCUPATION CD_STS_RESIDENTIAL_x  DEFAULT_AMT  \
0  Default Current- Missing             E                    R            0
1  Default Current- Missing             E                    R            0
2  Default Current- Missing             E                    O            0
3     Default Current1-1000             E                    R          459
4  Default Current- Missing             U                    B            0

   ...  WORST_24M                DOC_TYPE  VISA_TYPE  EMPLOYED_STATUS  \
0  ...        0.0  Intl Passport and Visa  Work Visa                E
1  ...        1.0       AU Driver Licence   Resident                E
2  ...        0.0       AU Driver Licence   Resident                E
3  ...        0.0  Intl Passport and Visa   Resident                E
4  ...        0.0  Intl Passport and Visa  Work Visa                U

   EMPLOYED_TYPE EMPLOYED_NO_MTHS NO_ADDRESS_AT_MONTHS  CD_STS_RESIDENTIAL_y  \
0              F              1.0                  1.0                     R
1              F             86.0                 49.0                     R
2              F             61.0                129.0                     O
3              F             15.0                 60.0                     R
4              U              0.0                  1.0                     B

   AGENCY_AMT  MTH_TILL_AGENCY
0         NaN              NaN
1         NaN              NaN
2         NaN              NaN
3         NaN              NaN
4       60.01             16.0

[5 rows x 98 columns]

In [4]:
merged_df

,OUTCOME,Customer,RISK_SCORE,BUREAU_ENQUIRIES_12_MONTHS,LICENCE_AVAILABLE,RESIDENTIAL,BUREAU_DEFAULT,CD_OCCUPATION,CD_STS_RESIDENTIAL_x,DEFAULT_AMT,...,WORST_24M,DOC_TYPE,VISA_TYPE,EMPLOYED_STATUS,EMPLOYED_TYPE,EMPLOYED_NO_MTHS,NO_ADDRESS_AT_MONTHS,CD_STS_RESIDENTIAL_y,AGENCY_AMT,MTH_TILL_AGENCY
0,Good,2975536526,628,queries 12 Months 1-2,Driver Licence Check Missing,Rented,Default Current- Missing,E,R,0,...,0.0,Intl Passport and Visa,Work Visa,E,F,1.0,1.0,R,NaN,NaN
1,Good,2999806086,813,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,86.0,49.0,R,NaN,NaN
2,Good,2800835182,1012,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,E,O,0,...,0.0,AU Driver Licence,Resident,E,F,61.0,129.0,O,NaN,NaN
3,Good,2975640662,415,queries 12 Months 4-5,Driver Licence Check Missing,Rented,Default Current1-1000,E,R,459,...,0.0,Intl Passport and Visa,Resident,E,F,15.0,60.0,R,NaN,NaN
4,Good,2979232086,556,queries 12 Months 1-2,Driver Licence Check Missing,Board or Living With Relative,Default Current- Missing,U,B,0,...,0.0,Intl Passport and Visa,Work Visa,U,U,0.0,1.0,B,60.01,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95304,Good,2999821794,1043,queries 12 Months 1-2,Driver Licence Check Yes,Owned,Default Current- Missing,R,O,0,...,0.0,AU Driver Licence,Resident,R,U,0.0,120.0,O,NaN,NaN
95305,Good,2811821694,589,queries 12 Months 6,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,1.0,6.0,R,NaN,NaN
95306,Good,2971478930,746,queries 12 Months 3,Driver Licence Check Missing,Owned,Default Current- Missing,S,O,0,...,0.0,AU Passport,Resident,S,F,0.0,125.0,O,NaN,NaN
95307,Bad,2974937898,868,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,U,R,0,...,0.0,AU Driver Licence,Resident,U,U,0.0,274.0,R,304.39,4.0
95308,Good,2977362690,1062,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,S,O,0,...,1.0,AU Driver Licence,Resident,S,F,120.0,120.0,O,NaN,NaN

### Removing duplicates

In [5]:
def remove_duplicates(merged_df):
    print("Removing the duplicates....")

    merged_df = merged_df.drop_duplicates()
    print("Duplicates removed sucessfully...")
    print(f"Dataset shape : {merged_df.shape}")

    return merged_df
merged_df = remove_duplicates(merged_df)
print("Remaining duplicates :",merged_df.duplicated().sum())

Removing the duplicates....
Duplicates removed sucessfully...
Dataset shape : (92115, 98)
Remaining duplicates : 0

In [6]:
merged_df.shape

(92115, 98)

In [7]:
merged_df

,OUTCOME,Customer,RISK_SCORE,BUREAU_ENQUIRIES_12_MONTHS,LICENCE_AVAILABLE,RESIDENTIAL,BUREAU_DEFAULT,CD_OCCUPATION,CD_STS_RESIDENTIAL_x,DEFAULT_AMT,...,WORST_24M,DOC_TYPE,VISA_TYPE,EMPLOYED_STATUS,EMPLOYED_TYPE,EMPLOYED_NO_MTHS,NO_ADDRESS_AT_MONTHS,CD_STS_RESIDENTIAL_y,AGENCY_AMT,MTH_TILL_AGENCY
0,Good,2975536526,628,queries 12 Months 1-2,Driver Licence Check Missing,Rented,Default Current- Missing,E,R,0,...,0.0,Intl Passport and Visa,Work Visa,E,F,1.0,1.0,R,NaN,NaN
1,Good,2999806086,813,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,86.0,49.0,R,NaN,NaN
2,Good,2800835182,1012,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,E,O,0,...,0.0,AU Driver Licence,Resident,E,F,61.0,129.0,O,NaN,NaN
3,Good,2975640662,415,queries 12 Months 4-5,Driver Licence Check Missing,Rented,Default Current1-1000,E,R,459,...,0.0,Intl Passport and Visa,Resident,E,F,15.0,60.0,R,NaN,NaN
4,Good,2979232086,556,queries 12 Months 1-2,Driver Licence Check Missing,Board or Living With Relative,Default Current- Missing,U,B,0,...,0.0,Intl Passport and Visa,Work Visa,U,U,0.0,1.0,B,60.01,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95304,Good,2999821794,1043,queries 12 Months 1-2,Driver Licence Check Yes,Owned,Default Current- Missing,R,O,0,...,0.0,AU Driver Licence,Resident,R,U,0.0,120.0,O,NaN,NaN
95305,Good,2811821694,589,queries 12 Months 6,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,1.0,6.0,R,NaN,NaN
95306,Good,2971478930,746,queries 12 Months 3,Driver Licence Check Missing,Owned,Default Current- Missing,S,O,0,...,0.0,AU Passport,Resident,S,F,0.0,125.0,O,NaN,NaN
95307,Bad,2974937898,868,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,U,R,0,...,0.0,AU Driver Licence,Resident,U,U,0.0,274.0,R,304.39,4.0
95308,Good,2977362690,1062,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,S,O,0,...,1.0,AU Driver Licence,Resident,S,F,120.0,120.0,O,NaN,NaN

### View the column summary

In [8]:
def column_summary(df):

    summary_df = pd.DataFrame({
        "Column_Name": df.columns,
        "Data_Type": df.dtypes.values,
        "Null_Count": df.isnull().sum().values,
        "Null_Percentage": round((df.isnull().sum() / len(df)) * 100, 2).values,
        "Unique_Values": df.nunique().values
    })

    summary_df = summary_df.sort_values(
        by="Null_Percentage",
        ascending=False
    )

    return summary_df


# Generate report
summary_df = column_summary(merged_df)

# View report
print(summary_df)
'''
#Save report
summary_df.to_csv(
    "Column_Summary_Report.csv",
    index=False
) '''

         Column_Name Data_Type  Null_Count  Null_Percentage  Unique_Values
96        AGENCY_AMT   float64       83495            90.64           8011
97   MTH_TILL_AGENCY   float64       83495            90.64             20
91   EMPLOYED_STATUS       str       11102            12.05              9
92     EMPLOYED_TYPE       str       11102            12.05              5
93  EMPLOYED_NO_MTHS   float64       11102            12.05            373
..               ...       ...         ...              ...            ...
13      DEFAULTS_12M     int64           0             0.00              6
14  NO_MONTHS_VCR221     int64           0             0.00             13
15  NO_STATUS_VCR183    object           0             0.00             12
16     CD_STS_VCR184    object           0             0.00             11
17  NO_MONTHS_VCR228     int64           0             0.00             25

[98 rows x 5 columns]

'\n#Save report\nsummary_df.to_csv(\n    "Column_Summary_Report.csv",\n    index=False\n) '

### Dropping the unwanted columns

In [9]:
def drop_unwanted_columns(df):

    columns_to_drop = [
        "Customer",
        "WORST_3M",
        "WORST_1M",
        "WORST_18M",
        "WORST_12M",
        "WORST_24M",
        "MTH_TILL_AGENCY",
        "AGENCY_AMT"
    ]

    print("Dropping unwanted columns...")

    df = df.drop(columns =columns_to_drop,errors="ignore")

    print("Dropping the columns sucessfully..")
    print(f"Current shape : {df.shape}")
    return df

merged_df = drop_unwanted_columns(merged_df)
print(merged_df.columns.tolist())

Dropping unwanted columns...
Dropping the columns sucessfully..
Current shape : (92115, 90)
['OUTCOME', 'RISK_SCORE', 'BUREAU_ENQUIRIES_12_MONTHS', 'LICENCE_AVAILABLE', 'RESIDENTIAL', 'BUREAU_DEFAULT', 'CD_OCCUPATION', 'CD_STS_RESIDENTIAL_x', 'DEFAULT_AMT', 'ENQUIRIES_6M', 'ENQUIRIES_12M', 'DEROGATORIES', 'DEFAULTS_12M', 'NO_MONTHS_VCR221', 'NO_STATUS_VCR183', 'CD_STS_VCR184', 'NO_MONTHS_VCR228', 'NO_MONTHS_VCR226', 'NO_SUM_VCR053', 'NO_MONTHS_VCR258', 'SCORECARD', 'NO_SCORE', 'SCORE_INDICATOR_CR22', 'SCORE_CR22', 'SCORE_BAND_CR22', 'NO_SCORE_CR21', 'SCORECARD_CR21', 'RISK_RELATIVE_CR21', 'RISK_RELATIVE_ODDS_CR21', 'NO_MONTHS_OLDEST_ACCOUNT', 'OPEN_ACCT_CR22', 'CLOSED_ACCT_CR22', 'MORTGAGE_CR22', 'CREDIT_CARD_CR22', 'TELCO_CR22', 'UTILITIES_CR22', 'OVERDRAFT_CR22', 'PERSONAL_LOAN_CR22', 'AUTO_LOAN_CR22', 'CREDIT_CARD_AMT_CR22', 'OVERDRAFT_AMT_CR22', 'PERSONAL_LOAN_AMT_CR22', 'AUTO_LOAN_AMT_CR22', 'OPEN_ACCT_CR21', 'CLOSED_ACCT_CR21', 'MORTGAGE_CR21', 'CREDIT_CARD_CR21', 'TELCO_CR21', 'UTILITIES_CR21', 'OVERDRAFT_CR21', 'PERSONAL_LOAN_CR21', 'AUTO_LOAN_CR21', 'CREDIT_CARD_AMT_CR21', 'OVERDRAFT_AMT_CR21', 'PERSONAL_LOAN_AMT_CR21', 'AUTO_LOAN_AMT_CR21', 'ENQUIRY_CNT_CR22', 'ENQUIRY_CNT_1M_CR22', 'ENQUIRY_CNT_3M_CR22', 'ENQUIRY_CNT_6M_CR22', 'ENQUIRY_CNT_12M_CR22', 'ENQUIRY_CNT_CR21', 'ENQUIRY_CNT_1M_CR21', 'ENQUIRY_CNT_3M_CR21', 'ENQUIRY_CNT_6M_CR21', 'ENQUIRY_CNT_12M_CR21', 'ENQUIRY_MAX_AMT_1M', 'ENQUIRY_MAX_AMT_3M', 'ENQUIRY_MAX_AMT_6M', 'ENQUIRY_MAX_AMT_12M', 'DEFAULT_CNT_CR22', 'DEFAULT_OPEN_CNT_CR22', 'DEFAULT_CNT_3M_CR22', 'DEFAULT_CNT_6M_CR22', 'DEFAULT_CNT_12M_CR22', 'DEFAULT_UNPAID_AMT_CR22', 'DEFAULT_CNT_CR21', 'DEFAULT_OPEN_CNT_CR21', 'DEFAULT_UNPAID_AMT_CR21', 'DEFAULT_CNT_3M_CR21', 'DEFAULT_CNT_6M_CR21', 'DEFAULT_CNT_12M_CR21', 'WORST_6M', 'DOC_TYPE', 'VISA_TYPE', 'EMPLOYED_STATUS', 'EMPLOYED_TYPE', 'EMPLOYED_NO_MTHS', 'NO_ADDRESS_AT_MONTHS', 'CD_STS_RESIDENTIAL_y']

In [10]:
merged_df

,OUTCOME,RISK_SCORE,BUREAU_ENQUIRIES_12_MONTHS,LICENCE_AVAILABLE,RESIDENTIAL,BUREAU_DEFAULT,CD_OCCUPATION,CD_STS_RESIDENTIAL_x,DEFAULT_AMT,ENQUIRIES_6M,...,DEFAULT_CNT_6M_CR21,DEFAULT_CNT_12M_CR21,WORST_6M,DOC_TYPE,VISA_TYPE,EMPLOYED_STATUS,EMPLOYED_TYPE,EMPLOYED_NO_MTHS,NO_ADDRESS_AT_MONTHS,CD_STS_RESIDENTIAL_y
0,Good,628,queries 12 Months 1-2,Driver Licence Check Missing,Rented,Default Current- Missing,E,R,0,2,...,0.0,0.0,0.0,Intl Passport and Visa,Work Visa,E,F,1.0,1.0,R
1,Good,813,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,2,...,0.0,0.0,1.0,AU Driver Licence,Resident,E,F,86.0,49.0,R
2,Good,1012,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,E,O,0,5,...,0.0,0.0,0.0,AU Driver Licence,Resident,E,F,61.0,129.0,O
3,Good,415,queries 12 Months 4-5,Driver Licence Check Missing,Rented,Default Current1-1000,E,R,459,2,...,0.0,0.0,0.0,Intl Passport and Visa,Resident,E,F,15.0,60.0,R
4,Good,556,queries 12 Months 1-2,Driver Licence Check Missing,Board or Living With Relative,Default Current- Missing,U,B,0,2,...,0.0,0.0,0.0,Intl Passport and Visa,Work Visa,U,U,0.0,1.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95304,Good,1043,queries 12 Months 1-2,Driver Licence Check Yes,Owned,Default Current- Missing,R,O,0,2,...,0.0,0.0,0.0,AU Driver Licence,Resident,R,U,0.0,120.0,O
95305,Good,589,queries 12 Months 6,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,3,...,0.0,0.0,1.0,AU Driver Licence,Resident,E,F,1.0,6.0,R
95306,Good,746,queries 12 Months 3,Driver Licence Check Missing,Owned,Default Current- Missing,S,O,0,3,...,0.0,0.0,0.0,AU Passport,Resident,S,F,0.0,125.0,O
95307,Bad,868,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,U,R,0,2,...,0.0,0.0,0.0,AU Driver Licence,Resident,U,U,0.0,274.0,R
95308,Good,1062,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,S,O,0,4,...,0.0,0.0,0.0,AU Driver Licence,Resident,S,F,120.0,120.0,O

### Imputing the missing values using "Mode and Median"

In [11]:
def impute_missing_values(df):
    print("Imputing the missing values")

    # Numeric columns:
    numerical_cols = df.select_dtypes(include=["int64","float64"]).columns

    for col in numerical_cols:
        df[col] = df[col].fillna(df[col].median())

    # categoriacal columns:
    categorical_cols = df.select_dtypes(include=["object"]).columns

    for col in categorical_cols:
        df[col] = df[col].fillna(df[col].mode()[0])

    print("Missiing values are Imputed successfully..")

    return df
merged_df = impute_missing_values(merged_df)
print(merged_df.isnull().sum().sum())

Imputing the missing values
Missiing values are Imputed successfully..
0

C:\Users\ompra\AppData\Local\Temp\ipykernel_15980\2243468637.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object"]).columns

In [12]:
merged_df.isnull().sum()

OUTCOME                       0
RISK_SCORE                    0
BUREAU_ENQUIRIES_12_MONTHS    0
LICENCE_AVAILABLE             0
RESIDENTIAL                   0
                             ..
EMPLOYED_STATUS               0
EMPLOYED_TYPE                 0
EMPLOYED_NO_MTHS              0
NO_ADDRESS_AT_MONTHS          0
CD_STS_RESIDENTIAL_y          0
Length: 90, dtype: int64

In [13]:
''''
erged_df.to_csv(
    "cleaned_data.csv",
    index=False
)

print("Cleaned dataset saved successfully.") '''

'\'\nerged_df.to_csv(\n    "cleaned_data.csv",\n    index=False\n)\n\nprint("Cleaned dataset saved successfully.") '


### Spliting the Target variables:

In [14]:
def split_features_target(df,target_column):

    print("Separating the feature and target variables...")

    x = df.drop(columns=[target_column])
    y= df[target_column]

    print("Features shape :",x.shape)
    print("Target shape :",y.shape)

    return x,y

x,y = split_features_target(merged_df,target_column="OUTCOME")

Separating the feature and target variables...
Features shape : (92115, 89)
Target shape : (92115,)

In [15]:
print(y.unique())
print(y.value_counts())

<StringArray>
['Good', 'Bad']
Length: 2, dtype: str
OUTCOME
Good    84478
Bad      7637
Name: count, dtype: int64

## EDA

### Target Variable Analysis :

In [29]:
def analyze_target(y):
    print("Target variable distribution..")
    print("-" * 40)

    print(y.value_counts())

    print("\nPercentage Distribution")
    print(round(y.value_counts(normalize=True) * 100, 2 ))



def analyze_numerical_features(x):
    """
    Analyze numerical columns.
    """

    print("\n" + "=" * 50)
    print("NUMERICAL FEATURE ANALYSIS")
    print("=" * 50)

    numerical_df = x.select_dtypes(
        include=["int64", "float64"]
    )

    print(numerical_df.describe().T)


def analyze_categorical_features(x):
    """
    Analyze categorical columns.
    """

    print("\n" + "=" * 50)
    print("CATEGORICAL FEATURE ANALYSIS")
    print("=" * 50)

    categorical_cols = x.select_dtypes(
        include=["object"]
    ).columns

    for col in categorical_cols:

        print("\n" + "-" * 50)
        print(f"Column : {col}")
        print("-" * 50)

        print(x[col].value_counts())


def target_correlation_analysis(x, y):
    """
    Correlation of numerical features
    with target variable.
    """

    print("\n" + "=" * 50)
    print("TARGET CORRELATION ANALYSIS")
    print("=" * 50)

    temp_df = x.copy()

    temp_df["OUTCOME"] = y

    correlation_df = (
        temp_df.corr(
            numeric_only=True
        )["OUTCOME"]
        .sort_values(
            ascending=False
        )
    )

    print(correlation_df)

    return correlation_df


def run_eda(x, y):
    """
    Execute complete EDA workflow.
    """

    analyze_target(y)

    analyze_numerical_features(x)

    analyze_categorical_features(x)

    correlation_df = target_correlation_analysis(x,y)

    return correlation_df

In [30]:
x, y = split_features_target(
    merged_df,
    target_column="OUTCOME"
)

Separating the feature and target variables...
Features shape : (92115, 89)
Target shape : (92115,)

In [31]:
y = y.map({
    "Good": 0,
    "Bad": 1
})

In [32]:
correlation_df = run_eda(x, y)

Target variable distribution..
----------------------------------------
OUTCOME
0    84478
1     7637
Name: count, dtype: int64

Percentage Distribution
OUTCOME
0    91.71
1     8.29
Name: proportion, dtype: float64

==================================================
NUMERICAL FEATURE ANALYSIS
==================================================
                        count        mean          std    min    25%    50%  \
RISK_SCORE            92115.0  720.987038   180.711410 -125.0  614.0  660.0
DEFAULT_AMT           92115.0  250.060077  4386.439734    0.0    0.0    0.0
ENQUIRIES_6M          92115.0    2.611735     1.453608    1.0    2.0    2.0
ENQUIRIES_12M         92115.0    2.993030     2.160077    1.0    2.0    2.0
DEROGATORIES          92115.0    0.256408     1.405470    0.0    0.0    0.0
...                       ...         ...          ...    ...    ...    ...
DEFAULT_CNT_6M_CR21   92115.0    0.001476     0.043186    0.0    0.0    0.0
DEFAULT_CNT_12M_CR21  92115.0    0.005613     0.086178    0.0    0.0    0.0
WORST_6M              92115.0    0.277436     0.954122    0.0    0.0    0.0
EMPLOYED_NO_MTHS      92115.0   22.187168    38.763209   -8.0    0.0    4.0
NO_ADDRESS_AT_MONTHS  92115.0   35.695348    51.054141    0.0    1.0   12.0

                        75%        max
RISK_SCORE            847.0     1157.0
DEFAULT_AMT             0.0  1017272.0
ENQUIRIES_6M            3.0      125.0
ENQUIRIES_12M           3.0      239.0
DEROGATORIES            0.0      253.0
...                     ...        ...
DEFAULT_CNT_6M_CR21     0.0        4.0
DEFAULT_CNT_12M_CR21    0.0        5.0
WORST_6M                0.0        8.0
EMPLOYED_NO_MTHS       25.0      720.0
NO_ADDRESS_AT_MONTHS   51.0      948.0

[72 rows x 8 columns]

==================================================
CATEGORICAL FEATURE ANALYSIS
==================================================

--------------------------------------------------
Column : BUREAU_ENQUIRIES_12_MONTHS
--------------------------------------------------
BUREAU_ENQUIRIES_12_MONTHS
queries 12 Months 1-2      57265
queries 12 Months 3        13967
queries 12 Months 4-5      13182
queries 12 Months 6         2806
queries 12 Months 8-11      2539
queries 12 Months 7         1614
queries 12 Months 12-14      454
queries 12 Months 14+        288
Name: count, dtype: int64

--------------------------------------------------
Column : LICENCE_AVAILABLE
--------------------------------------------------
LICENCE_AVAILABLE
Driver Licence Check Yes        56164
Driver Licence Check Missing    35722
Driver Licence Check No           229
Name: count, dtype: int64

--------------------------------------------------
Column : RESIDENTIAL
--------------------------------------------------
RESIDENTIAL
Rented                                       49289
Owned                                        25377
Board or Living With Relative                 9685
Living At Home                                6177
Residential Missing Not Willing To Supply     1587
Name: count, dtype: int64

--------------------------------------------------
Column : BUREAU_DEFAULT
--------------------------------------------------
BUREAU_DEFAULT
Default Current- Missing    87765
Default Current1000+         2769
Default Current1-1000        1581
Name: count, dtype: int64

--------------------------------------------------
Column : CD_OCCUPATION
--------------------------------------------------
CD_OCCUPATION
E          57502
Missing     8137
U           7423
S           6016
R           4603
P           3844
B           2400
Z           1298
H            625
T            267
Name: count, dtype: int64

--------------------------------------------------
Column : CD_STS_RESIDENTIAL_x
--------------------------------------------------
CD_STS_RESIDENTIAL_x
R          49136
O          25340
L           6157
B           5436
W           4228
Z           1583
Missing      235
Name: count, dtype: int64

--------------------------------------------------
Column : NO_STATUS_VCR183
--------------------------------------------------
NO_STATUS_VCR183
-    63241
0    10017
N     6076
1     5672
U     4538
2     1350
3      518
4      209
5      205
6      186
H       65
X       38
Name: count, dtype: int64

--------------------------------------------------
Column : CD_STS_VCR184
--------------------------------------------------
CD_STS_VCR184
-    82728
0     8506
1      419
2      140
N       97
3       90
X       52
4       35
5       17
H       16
6       15
Name: count, dtype: int64

--------------------------------------------------
Column : SCORECARD
--------------------------------------------------
SCORECARD
TAR1A     42734
SFJR1A    33902
CTSDP      8995
HSHSOL     6283
INSLV       201
Name: count, dtype: int64

--------------------------------------------------
Column : SCORE_INDICATOR_CR22
--------------------------------------------------
SCORE_INDICATOR_CR22
Clean Positive    86551
Dirty Positive     5564
Name: count, dtype: int64

--------------------------------------------------
Column : SCORE_BAND_CR22
--------------------------------------------------
SCORE_BAND_CR22
G    24309
A    20546
H    17641
F    14510
D     4557
C     4076
E     3212
B     3039
I      225
Name: count, dtype: int64

--------------------------------------------------
Column : SCORECARD_CR21
--------------------------------------------------
SCORECARD_CR21
CTS1A    46470
CTSSH    31167
CTSDP     8293
CTSAD     5990
INSLV      195
Name: count, dtype: int64

--------------------------------------------------
Column : DOC_TYPE
--------------------------------------------------
DOC_TYPE
AU Driver Licence                 58952
Intl Passport and Visa            26090
AU Passport                        5463
HAAU 18+ Card                       883
Australian Passport                 629
Fire Arms Licence                    84
Defence Force ID(picture card)       11
AU Birth Certificate                  3
Name: count, dtype: int64

--------------------------------------------------
Column : VISA_TYPE
--------------------------------------------------
VISA_TYPE
Resident     69927
Work Visa    19158
Student       3030
Name: count, dtype: int64

--------------------------------------------------
Column : EMPLOYED_STATUS
--------------------------------------------------
EMPLOYED_STATUS
E    66728
U     7274
S     5762
R     4423
P     3770
B     2313
Z     1009
H      573
T      263
Name: count, dtype: int64

--------------------------------------------------
Column : EMPLOYED_TYPE
--------------------------------------------------
EMPLOYED_TYPE
F    71391
U    13238
P     5086
S     1438
H      962
Name: count, dtype: int64

--------------------------------------------------
Column : CD_STS_RESIDENTIAL_y
--------------------------------------------------
CD_STS_RESIDENTIAL_y
R    51054
O    24353
L     5954
B     5293
W     4118
Z     1343
Name: count, dtype: int64

==================================================
TARGET CORRELATION ANALYSIS
==================================================

C:\Users\ompra\AppData\Local\Temp\ipykernel_15980\3165039540.py:37: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = x.select_dtypes(

OUTCOME                  1.000000
DEFAULT_OPEN_CNT_CR21    0.204732
DEFAULT_CNT_CR21         0.202649
DEROGATORIES             0.169665
WORST_6M                 0.127472
                           ...
NO_SCORE_CR21           -0.210762
NO_SCORE                -0.214745
SCORE_CR22              -0.219520
RISK_SCORE              -0.223569
CREDIT_CARD_AMT_CR21          NaN
Name: OUTCOME, Length: 73, dtype: float64

## Feature Engineering

In [34]:
# Check Remaining Categorical Columns

categorical_cols = x.select_dtypes(include = ["object"]).columns
print("Categorical Columns.")
print(categorical_cols.to_list())

Categorical Columns.
['BUREAU_ENQUIRIES_12_MONTHS', 'LICENCE_AVAILABLE', 'RESIDENTIAL', 'BUREAU_DEFAULT', 'CD_OCCUPATION', 'CD_STS_RESIDENTIAL_x', 'NO_STATUS_VCR183', 'CD_STS_VCR184', 'SCORECARD', 'SCORE_INDICATOR_CR22', 'SCORE_BAND_CR22', 'SCORECARD_CR21', 'DOC_TYPE', 'VISA_TYPE', 'EMPLOYED_STATUS', 'EMPLOYED_TYPE', 'CD_STS_RESIDENTIAL_y']

C:\Users\ompra\AppData\Local\Temp\ipykernel_15980\2415548192.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = x.select_dtypes(include = ["object"]).columns

In [35]:
# Analyze Cardinality
# Checking how many unique values each categorical column contains.

def analyze_categorical_columns(x):

    categorical_cols = x.select_dtypes(include=["object"])

    for col in categorical_cols:
        print("\n" + "=" * 50)
        print(f"Column : {col}")
        print("=" * 50)

        print(
            x[col].value_counts()
        )

        print(
            f"Unique Values : {x[col].nunique()}"
        )

analyze_categorical_columns(x)

C:\Users\ompra\AppData\Local\Temp\ipykernel_15980\3868536597.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = x.select_dtypes(include=["object"])

==================================================
Column : BUREAU_ENQUIRIES_12_MONTHS
==================================================
BUREAU_ENQUIRIES_12_MONTHS
queries 12 Months 1-2      57265
queries 12 Months 3        13967
queries 12 Months 4-5      13182
queries 12 Months 6         2806
queries 12 Months 8-11      2539
queries 12 Months 7         1614
queries 12 Months 12-14      454
queries 12 Months 14+        288
Name: count, dtype: int64
Unique Values : 8

==================================================
Column : LICENCE_AVAILABLE
==================================================
LICENCE_AVAILABLE
Driver Licence Check Yes        56164
Driver Licence Check Missing    35722
Driver Licence Check No           229
Name: count, dtype: int64
Unique Values : 3

==================================================
Column : RESIDENTIAL
==================================================
RESIDENTIAL
Rented                                       49289
Owned                                        25377
Board or Living With Relative                 9685
Living At Home                                6177
Residential Missing Not Willing To Supply     1587
Name: count, dtype: int64
Unique Values : 5

==================================================
Column : BUREAU_DEFAULT
==================================================
BUREAU_DEFAULT
Default Current- Missing    87765
Default Current1000+         2769
Default Current1-1000        1581
Name: count, dtype: int64
Unique Values : 3

==================================================
Column : CD_OCCUPATION
==================================================
CD_OCCUPATION
E          57502
Missing     8137
U           7423
S           6016
R           4603
P           3844
B           2400
Z           1298
H            625
T            267
Name: count, dtype: int64
Unique Values : 10

==================================================
Column : CD_STS_RESIDENTIAL_x
==================================================
CD_STS_RESIDENTIAL_x
R          49136
O          25340
L           6157
B           5436
W           4228
Z           1583
Missing      235
Name: count, dtype: int64
Unique Values : 7

==================================================
Column : NO_STATUS_VCR183
==================================================
NO_STATUS_VCR183
-    63241
0    10017
N     6076
1     5672
U     4538
2     1350
3      518
4      209
5      205
6      186
H       65
X       38
Name: count, dtype: int64
Unique Values : 12

==================================================
Column : CD_STS_VCR184
==================================================
CD_STS_VCR184
-    82728
0     8506
1      419
2      140
N       97
3       90
X       52
4       35
5       17
H       16
6       15
Name: count, dtype: int64
Unique Values : 11

==================================================
Column : SCORECARD
==================================================
SCORECARD
TAR1A     42734
SFJR1A    33902
CTSDP      8995
HSHSOL     6283
INSLV       201
Name: count, dtype: int64
Unique Values : 5

==================================================
Column : SCORE_INDICATOR_CR22
==================================================
SCORE_INDICATOR_CR22
Clean Positive    86551
Dirty Positive     5564
Name: count, dtype: int64
Unique Values : 2

==================================================
Column : SCORE_BAND_CR22
==================================================
SCORE_BAND_CR22
G    24309
A    20546
H    17641
F    14510
D     4557
C     4076
E     3212
B     3039
I      225
Name: count, dtype: int64
Unique Values : 9

==================================================
Column : SCORECARD_CR21
==================================================
SCORECARD_CR21
CTS1A    46470
CTSSH    31167
CTSDP     8293
CTSAD     5990
INSLV      195
Name: count, dtype: int64
Unique Values : 5

==================================================
Column : DOC_TYPE
==================================================
DOC_TYPE
AU Driver Licence                 58952
Intl Passport and Visa            26090
AU Passport                        5463
HAAU 18+ Card                       883
Australian Passport                 629
Fire Arms Licence                    84
Defence Force ID(picture card)       11
AU Birth Certificate                  3
Name: count, dtype: int64
Unique Values : 8

==================================================
Column : VISA_TYPE
==================================================
VISA_TYPE
Resident     69927
Work Visa    19158
Student       3030
Name: count, dtype: int64
Unique Values : 3

==================================================
Column : EMPLOYED_STATUS
==================================================
EMPLOYED_STATUS
E    66728
U     7274
S     5762
R     4423
P     3770
B     2313
Z     1009
H      573
T      263
Name: count, dtype: int64
Unique Values : 9

==================================================
Column : EMPLOYED_TYPE
==================================================
EMPLOYED_TYPE
F    71391
U    13238
P     5086
S     1438
H      962
Name: count, dtype: int64
Unique Values : 5

==================================================
Column : CD_STS_RESIDENTIAL_y
==================================================
CD_STS_RESIDENTIAL_y
R    51054
O    24353
L     5954
B     5293
W     4118
Z     1343
Name: count, dtype: int64
Unique Values : 6

In [36]:
#Next Step: Create a Feature Engineering Report

#Don't encode immediately.

#First create a report.


def categorical_feature_report(x):

    categorical_cols = x.select_dtypes(
        include=["object"]
    ).columns

    report = []

    for col in categorical_cols:

        report.append({
            "Column_Name": col,
            "Unique_Values": x[col].nunique(),
            "Most_Frequent_Value": x[col].mode()[0]
        })

    return pd.DataFrame(report)


cat_report = categorical_feature_report(x)

print(cat_report)

C:\Users\ompra\AppData\Local\Temp\ipykernel_15980\2977386533.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = x.select_dtypes(

                   Column_Name  Unique_Values       Most_Frequent_Value
0   BUREAU_ENQUIRIES_12_MONTHS              8     queries 12 Months 1-2
1            LICENCE_AVAILABLE              3  Driver Licence Check Yes
2                  RESIDENTIAL              5                    Rented
3               BUREAU_DEFAULT              3  Default Current- Missing
4                CD_OCCUPATION             10                         E
5         CD_STS_RESIDENTIAL_x              7                         R
6             NO_STATUS_VCR183             12                         -
7                CD_STS_VCR184             11                         -
8                    SCORECARD              5                     TAR1A
9         SCORE_INDICATOR_CR22              2            Clean Positive
10             SCORE_BAND_CR22              9                         G
11              SCORECARD_CR21              5                     CTS1A
12                    DOC_TYPE              8         AU Driver Licence
13                   VISA_TYPE              3                  Resident
14             EMPLOYED_STATUS              9                         E
15               EMPLOYED_TYPE              5                         F
16        CD_STS_RESIDENTIAL_y              6                         R

In [37]:
#Create an encoding function.

def encode_categorical_features(x):

    print("Encoding categorical features...")

    x_encoded = pd.get_dummies(
        x,
        drop_first=True
    )

    print("Encoding completed.")
    print(f"Shape Before Encoding : {x.shape}")
    print(f"Shape After Encoding  : {x_encoded.shape}")

    return x_encoded

x_encoded = encode_categorical_features(x)

print(
    x_encoded.select_dtypes(
        include=["object","string"]
    ).columns.tolist()
)

Encoding categorical features...
Encoding completed.
Shape Before Encoding : (92115, 89)
Shape After Encoding  : (92115, 166)
[]

In [ ]:
# checking dtypes of the columns
print( x_encoded.dtypes.value_counts())

bool       94
float64    60
int64      12
Name: count, dtype: int64

In [39]:
x

,RISK_SCORE,BUREAU_ENQUIRIES_12_MONTHS,LICENCE_AVAILABLE,RESIDENTIAL,BUREAU_DEFAULT,CD_OCCUPATION,CD_STS_RESIDENTIAL_x,DEFAULT_AMT,ENQUIRIES_6M,ENQUIRIES_12M,...,DEFAULT_CNT_6M_CR21,DEFAULT_CNT_12M_CR21,WORST_6M,DOC_TYPE,VISA_TYPE,EMPLOYED_STATUS,EMPLOYED_TYPE,EMPLOYED_NO_MTHS,NO_ADDRESS_AT_MONTHS,CD_STS_RESIDENTIAL_y
0,628,queries 12 Months 1-2,Driver Licence Check Missing,Rented,Default Current- Missing,E,R,0,2,2,...,0.0,0.0,0.0,Intl Passport and Visa,Work Visa,E,F,1.0,1.0,R
1,813,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,2,2,...,0.0,0.0,1.0,AU Driver Licence,Resident,E,F,86.0,49.0,R
2,1012,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,E,O,0,5,5,...,0.0,0.0,0.0,AU Driver Licence,Resident,E,F,61.0,129.0,O
3,415,queries 12 Months 4-5,Driver Licence Check Missing,Rented,Default Current1-1000,E,R,459,2,4,...,0.0,0.0,0.0,Intl Passport and Visa,Resident,E,F,15.0,60.0,R
4,556,queries 12 Months 1-2,Driver Licence Check Missing,Board or Living With Relative,Default Current- Missing,U,B,0,2,2,...,0.0,0.0,0.0,Intl Passport and Visa,Work Visa,U,U,0.0,1.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95304,1043,queries 12 Months 1-2,Driver Licence Check Yes,Owned,Default Current- Missing,R,O,0,2,2,...,0.0,0.0,0.0,AU Driver Licence,Resident,R,U,0.0,120.0,O
95305,589,queries 12 Months 6,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,3,6,...,0.0,0.0,1.0,AU Driver Licence,Resident,E,F,1.0,6.0,R
95306,746,queries 12 Months 3,Driver Licence Check Missing,Owned,Default Current- Missing,S,O,0,3,3,...,0.0,0.0,0.0,AU Passport,Resident,S,F,0.0,125.0,O
95307,868,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,U,R,0,2,2,...,0.0,0.0,0.0,AU Driver Licence,Resident,U,U,0.0,274.0,R
95308,1062,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,S,O,0,4,4,...,0.0,0.0,0.0,AU Driver Licence,Resident,S,F,120.0,120.0,O

In [41]:
print(x_encoded.head(10))

   RISK_SCORE  DEFAULT_AMT  ENQUIRIES_6M  ENQUIRIES_12M  DEROGATORIES  \
0         628            0             2              2             0
1         813            0             2              2             0
2        1012            0             5              5             0
3         415          459             2              4             1
4         556            0             2              2             0
5         497          215             2              2             1
6         626            0             2              2             0
7         613            0             2              2             0
8         603            0             2              2             0
9         657            0             3              3             0

   DEFAULTS_12M  NO_MONTHS_VCR221  NO_MONTHS_VCR228  NO_MONTHS_VCR226  \
0             0                 0                 0                 0
1             0                 0                24                 0
2             0                 0                24                 0
3             0                 0                 0                 0
4             0                 0                 0                 0
5             0                 4                18                 4
6             0                 0                 0                 0
7             0                 0                 0                 0
8             0                 0                 0                 0
9             0                 0                 0                 0

   NO_SUM_VCR053  ...  EMPLOYED_STATUS_Z  EMPLOYED_TYPE_H  EMPLOYED_TYPE_P  \
0              0  ...              False            False            False
1           4000  ...              False            False            False
2         380277  ...              False            False            False
3              0  ...              False            False            False
4              0  ...              False            False            False
5           2000  ...              False            False            False
6              0  ...              False            False            False
7              0  ...              False            False            False
8              0  ...              False            False            False
9              0  ...              False            False            False

   EMPLOYED_TYPE_S  EMPLOYED_TYPE_U  CD_STS_RESIDENTIAL_y_L  \
0            False            False                   False
1            False            False                   False
2            False            False                   False
3            False            False                   False
4            False             True                   False
5            False            False                   False
6            False            False                   False
7            False            False                   False
8            False             True                   False
9            False            False                   False

   CD_STS_RESIDENTIAL_y_O  CD_STS_RESIDENTIAL_y_R  CD_STS_RESIDENTIAL_y_W  \
0                   False                    True                   False
1                   False                    True                   False
2                    True                   False                   False
3                   False                    True                   False
4                   False                   False                   False
5                   False                    True                   False
6                   False                    True                   False
7                   False                   False                   False
8                   False                    True                   False
9                   False                    True                   False

   CD_STS_RESIDENTIAL_y_Z
0                   False
1                   False
2                   False
3                   False
4                   False
5                   False
6                   False
7                   False
8                   False
9                   False

[10 rows x 166 columns]

In [42]:
print("Shape:", x_encoded.shape)

Shape: (92115, 166)