# Merging the datasets

In [1]:
import pandas as pd

In [6]:
# Load datasets

df_data = pd.read_excel("Data.xlsm",sheet_name="DataV2")
df_additional = pd.read_excel("Additional Info.xlsx",sheet_name="Additional info")

# Merging the datasets
merged_df = pd.merge(df_data,df_additional,on="Customer",how="left")

# save the file
merged_df.to_excel("Merged_Datasets.xlsx",index=False)

print("Merged Successfully !!")
print("Final Shape",merged_df.shape)

Merged Successfully !!
Final Shape (95309, 98)

In [7]:
merged_df

,OUTCOME,Customer,RISK_SCORE,BUREAU_ENQUIRIES_12_MONTHS,LICENCE_AVAILABLE,RESIDENTIAL,BUREAU_DEFAULT,CD_OCCUPATION,CD_STS_RESIDENTIAL_x,DEFAULT_AMT,...,WORST_24M,DOC_TYPE,VISA_TYPE,EMPLOYED_STATUS,EMPLOYED_TYPE,EMPLOYED_NO_MTHS,NO_ADDRESS_AT_MONTHS,CD_STS_RESIDENTIAL_y,AGENCY_AMT,MTH_TILL_AGENCY
0,Good,2975536526,628,queries 12 Months 1-2,Driver Licence Check Missing,Rented,Default Current- Missing,E,R,0,...,0.0,Intl Passport and Visa,Work Visa,E,F,1.0,1.0,R,NaN,NaN
1,Good,2999806086,813,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,86.0,49.0,R,NaN,NaN
2,Good,2800835182,1012,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,E,O,0,...,0.0,AU Driver Licence,Resident,E,F,61.0,129.0,O,NaN,NaN
3,Good,2975640662,415,queries 12 Months 4-5,Driver Licence Check Missing,Rented,Default Current1-1000,E,R,459,...,0.0,Intl Passport and Visa,Resident,E,F,15.0,60.0,R,NaN,NaN
4,Good,2979232086,556,queries 12 Months 1-2,Driver Licence Check Missing,Board or Living With Relative,Default Current- Missing,U,B,0,...,0.0,Intl Passport and Visa,Work Visa,U,U,0.0,1.0,B,60.01,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95304,Good,2999821794,1043,queries 12 Months 1-2,Driver Licence Check Yes,Owned,Default Current- Missing,R,O,0,...,0.0,AU Driver Licence,Resident,R,U,0.0,120.0,O,NaN,NaN
95305,Good,2811821694,589,queries 12 Months 6,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,1.0,6.0,R,NaN,NaN
95306,Good,2971478930,746,queries 12 Months 3,Driver Licence Check Missing,Owned,Default Current- Missing,S,O,0,...,0.0,AU Passport,Resident,S,F,0.0,125.0,O,NaN,NaN
95307,Bad,2974937898,868,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,U,R,0,...,0.0,AU Driver Licence,Resident,U,U,0.0,274.0,R,304.39,4.0
95308,Good,2977362690,1062,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,S,O,0,...,1.0,AU Driver Licence,Resident,S,F,120.0,120.0,O,NaN,NaN

## Data Cleaning

In [9]:
# Load merged datasets
merged_df = pd.read_excel("Merged_Datasets.xlsx")

#Check duplicate clonts
duplicated_counts = merged_df.duplicated().sum()
print(f"Duplicated Rows found : {duplicated_counts}")

# Remove duplicated
merged_df = merged_df.drop_duplicates()
print(f"Final Shape : {merged_df.shape}")

# save cleaned datasets
merged_df.to_csv("Merged_datasets_No_duplictes.csv",index=False)
print("Duplicates removed successfully")

Duplicated Rows found : 3167
Final Shape : (92142, 98)
Duplicates removed successfully

In [10]:
merged_df

,OUTCOME,Customer,RISK_SCORE,BUREAU_ENQUIRIES_12_MONTHS,LICENCE_AVAILABLE,RESIDENTIAL,BUREAU_DEFAULT,CD_OCCUPATION,CD_STS_RESIDENTIAL_x,DEFAULT_AMT,...,WORST_24M,DOC_TYPE,VISA_TYPE,EMPLOYED_STATUS,EMPLOYED_TYPE,EMPLOYED_NO_MTHS,NO_ADDRESS_AT_MONTHS,CD_STS_RESIDENTIAL_y,AGENCY_AMT,MTH_TILL_AGENCY
0,Good,2975536526,628,queries 12 Months 1-2,Driver Licence Check Missing,Rented,Default Current- Missing,E,R,0,...,0.0,Intl Passport and Visa,Work Visa,E,F,1.0,1.0,R,NaN,NaN
1,Good,2999806086,813,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,86.0,49.0,R,NaN,NaN
2,Good,2800835182,1012,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,E,O,0,...,0.0,AU Driver Licence,Resident,E,F,61.0,129.0,O,NaN,NaN
3,Good,2975640662,415,queries 12 Months 4-5,Driver Licence Check Missing,Rented,Default Current1-1000,E,R,459,...,0.0,Intl Passport and Visa,Resident,E,F,15.0,60.0,R,NaN,NaN
4,Good,2979232086,556,queries 12 Months 1-2,Driver Licence Check Missing,Board or Living With Relative,Default Current- Missing,U,B,0,...,0.0,Intl Passport and Visa,Work Visa,U,U,0.0,1.0,B,60.01,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95304,Good,2999821794,1043,queries 12 Months 1-2,Driver Licence Check Yes,Owned,Default Current- Missing,R,O,0,...,0.0,AU Driver Licence,Resident,R,U,0.0,120.0,O,NaN,NaN
95305,Good,2811821694,589,queries 12 Months 6,Driver Licence Check Yes,Rented,Default Current- Missing,E,R,0,...,1.0,AU Driver Licence,Resident,E,F,1.0,6.0,R,NaN,NaN
95306,Good,2971478930,746,queries 12 Months 3,Driver Licence Check Missing,Owned,Default Current- Missing,S,O,0,...,0.0,AU Passport,Resident,S,F,0.0,125.0,O,NaN,NaN
95307,Bad,2974937898,868,queries 12 Months 1-2,Driver Licence Check Yes,Rented,Default Current- Missing,U,R,0,...,0.0,AU Driver Licence,Resident,U,U,0.0,274.0,R,304.39,4.0
95308,Good,2977362690,1062,queries 12 Months 4-5,Driver Licence Check Yes,Owned,Default Current- Missing,S,O,0,...,1.0,AU Driver Licence,Resident,S,F,120.0,120.0,O,NaN,NaN

In [11]:
merged_df.OUTCOME.unique()

<StringArray>
['Good', 'Bad', 'Rejected - Policy Decline']
Length: 3, dtype: str

In [13]:
merged_df.columns.unique()

Index(['OUTCOME', 'Customer', 'RISK_SCORE', 'BUREAU_ENQUIRIES_12_MONTHS',
       'LICENCE_AVAILABLE', 'RESIDENTIAL', 'BUREAU_DEFAULT', 'CD_OCCUPATION',
       'CD_STS_RESIDENTIAL_x', 'DEFAULT_AMT', 'ENQUIRIES_6M', 'ENQUIRIES_12M',
       'DEROGATORIES', 'DEFAULTS_12M', 'NO_MONTHS_VCR221', 'NO_STATUS_VCR183',
       'CD_STS_VCR184', 'NO_MONTHS_VCR228', 'NO_MONTHS_VCR226',
       'NO_SUM_VCR053', 'NO_MONTHS_VCR258', 'SCORECARD', 'NO_SCORE',
       'SCORE_INDICATOR_CR22', 'SCORE_CR22', 'SCORE_BAND_CR22',
       'NO_SCORE_CR21', 'SCORECARD_CR21', 'RISK_RELATIVE_CR21',
       'RISK_RELATIVE_ODDS_CR21', 'NO_MONTHS_OLDEST_ACCOUNT', 'OPEN_ACCT_CR22',
       'CLOSED_ACCT_CR22', 'MORTGAGE_CR22', 'CREDIT_CARD_CR22', 'TELCO_CR22',
       'UTILITIES_CR22', 'OVERDRAFT_CR22', 'PERSONAL_LOAN_CR22',
       'AUTO_LOAN_CR22', 'CREDIT_CARD_AMT_CR22', 'OVERDRAFT_AMT_CR22',
       'PERSONAL_LOAN_AMT_CR22', 'AUTO_LOAN_AMT_CR22', 'OPEN_ACCT_CR21',
       'CLOSED_ACCT_CR21', 'MORTGAGE_CR21', 'CREDIT_CARD_CR21', 'TELCO_CR21',
       'UTILITIES_CR21', 'OVERDRAFT_CR21', 'PERSONAL_LOAN_CR21',
       'AUTO_LOAN_CR21', 'CREDIT_CARD_AMT_CR21', 'OVERDRAFT_AMT_CR21',
       'PERSONAL_LOAN_AMT_CR21', 'AUTO_LOAN_AMT_CR21', 'ENQUIRY_CNT_CR22',
       'ENQUIRY_CNT_1M_CR22', 'ENQUIRY_CNT_3M_CR22', 'ENQUIRY_CNT_6M_CR22',
       'ENQUIRY_CNT_12M_CR22', 'ENQUIRY_CNT_CR21', 'ENQUIRY_CNT_1M_CR21',
       'ENQUIRY_CNT_3M_CR21', 'ENQUIRY_CNT_6M_CR21', 'ENQUIRY_CNT_12M_CR21',
       'ENQUIRY_MAX_AMT_1M', 'ENQUIRY_MAX_AMT_3M', 'ENQUIRY_MAX_AMT_6M',
       'ENQUIRY_MAX_AMT_12M', 'DEFAULT_CNT_CR22', 'DEFAULT_OPEN_CNT_CR22',
       'DEFAULT_CNT_3M_CR22', 'DEFAULT_CNT_6M_CR22', 'DEFAULT_CNT_12M_CR22',
       'DEFAULT_UNPAID_AMT_CR22', 'DEFAULT_CNT_CR21', 'DEFAULT_OPEN_CNT_CR21',
       'DEFAULT_UNPAID_AMT_CR21', 'DEFAULT_CNT_3M_CR21', 'DEFAULT_CNT_6M_CR21',
       'DEFAULT_CNT_12M_CR21', 'WORST_1M', 'WORST_3M', 'WORST_6M', 'WORST_12M',
       'WORST_18M', 'WORST_24M', 'DOC_TYPE', 'VISA_TYPE', 'EMPLOYED_STATUS',
       'EMPLOYED_TYPE', 'EMPLOYED_NO_MTHS', 'NO_ADDRESS_AT_MONTHS',
       'CD_STS_RESIDENTIAL_y', 'AGENCY_AMT', 'MTH_TILL_AGENCY'],
      dtype='str')